services:
  pihole:
    image: pihole/pihole
    container_name: Pi-Hole
    network_mode: host
    security_opt:
      - no-new-privileges:false
    restart: on-failure:5
    volumes:
      - /volume1/docker/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
      - /volume1/docker/pihole/pihole:/etc/pihole:rw
    environment:
      FTLCONF_webserver_api_password: ${PIHOLE_API_PASSWORD:-Password!}
      FTLCONF_webserver_port: 8080
      FTLCONF_dns_listeningMode: all
      TZ: ${TZ:-America/New_York}
      DNSMASQ_USER: ${DNSMASQ_USER:-pihole}
      PIHOLE_UID: ${PIHOLE_UID:-1026}
      PIHOLE_GID: ${PIHOLE_GID:-100}
    cap_add:
      - SYS_TIME
      - SYS_NICE
